// <auto-generated />
using KRFHomepage.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KRFHomepage.Infrastructure.Migrations
{
    [DbContext(typeof(HomepageDBContext))]
    [Migration("20210204191327_InitializeDatabase")]
    partial class InitializeDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("KRFHomepage.Domain.Database.Common.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code")
                        .HasName("PK_LANGUAGE");

                    b.ToTable("languages");

                    b.HasData(
                        new
                        {
                            Code = "PT",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Code = "EN",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Homepage.HomePageData", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LanguageCode")
                        .HasName("PK_HOMEPAGE");

                    b.ToTable("homepages");

                    b.HasData(
                        new
                        {
                            LanguageCode = "PT",
                            Description = "Bem Vindo ao KRF, isto é uma framework react para fazer desenvolvimento divertido :)",
                            SubTitle = "A página principal do KRF com microserviços",
                            Title = "KJohn React Framework"
                        },
                        new
                        {
                            LanguageCode = "EN",
                            Description = "Welcome to KRF, this is a react framework to make some fun dev :)",
                            SubTitle = "The KRF homepage with microservices",
                            Title = "KJohn React Framework"
                        });
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.ErrorCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Code")
                        .HasName("PK_ErrorCode");

                    b.ToTable("error_code");

                    b.HasData(
                        new
                        {
                            Code = "GenericError"
                        },
                        new
                        {
                            Code = "PageNotFound"
                        },
                        new
                        {
                            Code = "AdminOnlyError"
                        },
                        new
                        {
                            Code = "AbortError"
                        });
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.ErrorTranslation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("PK_ErrorTranslations");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("Code", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("IN_ErrorTranslation_ErrorCode_LanguageCode");

                    b.ToTable("error_translations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "GenericError",
                            LanguageCode = "PT",
                            Message = "Erro Genérico",
                            Title = "Erro Genérico"
                        },
                        new
                        {
                            ID = 2,
                            Code = "PageNotFound",
                            LanguageCode = "PT",
                            Message = "Página não encontrada",
                            Title = "Página não encontrada"
                        },
                        new
                        {
                            ID = 3,
                            Code = "AdminOnlyError",
                            LanguageCode = "PT",
                            Message = "Página só se encontrada disponível para administração!",
                            Title = "Apenas Administrador"
                        },
                        new
                        {
                            ID = 4,
                            Code = "AbortError",
                            LanguageCode = "PT",
                            Message = "A chamada ao serviço foi abortada ou terminou o tempo de espera",
                            Title = "Chamada a serviço abortada"
                        },
                        new
                        {
                            ID = 5,
                            Code = "GenericError",
                            LanguageCode = "EN",
                            Message = "Generic Error",
                            Title = "Generic Error"
                        },
                        new
                        {
                            ID = 6,
                            Code = "PageNotFound",
                            LanguageCode = "EN",
                            Message = "Page not found",
                            Title = "Page not found"
                        },
                        new
                        {
                            ID = 7,
                            Code = "AdminOnlyError",
                            LanguageCode = "EN",
                            Message = "This page is only available for administration!",
                            Title = "Administrator Only"
                        },
                        new
                        {
                            ID = 8,
                            Code = "AbortError",
                            LanguageCode = "EN",
                            Message = "The call to service was aborted or service Timed Out",
                            Title = "Aborted service call"
                        });
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.Token", b =>
                {
                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Value")
                        .HasName("PK_TOKEN");

                    b.ToTable("tokens");

                    b.HasData(
                        new
                        {
                            Value = "#(loadingText)"
                        },
                        new
                        {
                            Value = "#(goBackToHome)"
                        },
                        new
                        {
                            Value = "#(goBackToHomeToolTip)"
                        },
                        new
                        {
                            Value = "#(cardDetails)"
                        },
                        new
                        {
                            Value = "#(edit)"
                        },
                        new
                        {
                            Value = "#(remove)"
                        },
                        new
                        {
                            Value = "#(TestPage Title)"
                        },
                        new
                        {
                            Value = "#(January)"
                        },
                        new
                        {
                            Value = "#(February)"
                        },
                        new
                        {
                            Value = "#(March)"
                        },
                        new
                        {
                            Value = "#(April)"
                        },
                        new
                        {
                            Value = "#(May)"
                        },
                        new
                        {
                            Value = "#(June)"
                        },
                        new
                        {
                            Value = "#(July)"
                        },
                        new
                        {
                            Value = "#(August)"
                        },
                        new
                        {
                            Value = "#(September)"
                        },
                        new
                        {
                            Value = "#(October)"
                        },
                        new
                        {
                            Value = "#(November)"
                        },
                        new
                        {
                            Value = "#(December)"
                        },
                        new
                        {
                            Value = "#(Mon)"
                        },
                        new
                        {
                            Value = "#(Tue)"
                        },
                        new
                        {
                            Value = "#(Wed)"
                        },
                        new
                        {
                            Value = "#(Thu)"
                        },
                        new
                        {
                            Value = "#(Fri)"
                        },
                        new
                        {
                            Value = "#(Sat)"
                        },
                        new
                        {
                            Value = "#(Sun)"
                        },
                        new
                        {
                            Value = "#(Cancel)"
                        },
                        new
                        {
                            Value = "#(krf)"
                        },
                        new
                        {
                            Value = "#(User)"
                        },
                        new
                        {
                            Value = "#(Administration)"
                        },
                        new
                        {
                            Value = "#(Logout)"
                        },
                        new
                        {
                            Value = "#(Test1)"
                        },
                        new
                        {
                            Value = "#(Test2)"
                        },
                        new
                        {
                            Value = "#(SubTest1)"
                        },
                        new
                        {
                            Value = "#(SubTest2)"
                        },
                        new
                        {
                            Value = "#(Username)"
                        },
                        new
                        {
                            Value = "#(Password)"
                        },
                        new
                        {
                            Value = "#(LoginButton)"
                        },
                        new
                        {
                            Value = "#(LoginDrop)"
                        },
                        new
                        {
                            Value = "#(NewLogin)"
                        },
                        new
                        {
                            Value = "#(Tooltip)"
                        },
                        new
                        {
                            Value = "#(NotificationHeader)"
                        },
                        new
                        {
                            Value = "#(FromDateToDate)"
                        },
                        new
                        {
                            Value = "#(OldUnreadedNotification)"
                        },
                        new
                        {
                            Value = "#(ViewAll)"
                        },
                        new
                        {
                            Value = "#(Yes)"
                        },
                        new
                        {
                            Value = "#(No)"
                        },
                        new
                        {
                            Value = "#(Ok)"
                        },
                        new
                        {
                            Value = "#(ModalTest1)"
                        },
                        new
                        {
                            Value = "#(ModalTest2)"
                        },
                        new
                        {
                            Value = "#(CookiesModal)"
                        },
                        new
                        {
                            Value = "#(CookiesModalDescription)"
                        },
                        new
                        {
                            Value = "#(CookieAnalyticDescription)"
                        },
                        new
                        {
                            Value = "#(CookieKey)"
                        },
                        new
                        {
                            Value = "#(CookieDescription)"
                        },
                        new
                        {
                            Value = "#(no_option)"
                        },
                        new
                        {
                            Value = "#(opt_2)"
                        });
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.Translation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TranslationCategoryValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID")
                        .HasName("PK_TRANSLATIONS");

                    b.HasIndex("TokenValue");

                    b.HasIndex("TranslationCategoryValue");

                    b.HasIndex("LanguageCode", "TokenValue", "TranslationCategoryValue")
                        .IsUnique()
                        .HasDatabaseName("IN_TRANSLATIONS_LanguageCode_TokenValue_TranslationCategoryValue");

                    b.ToTable("translations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LanguageCode = "PT",
                            Text = "A Carregar!",
                            TokenValue = "#(loadingText)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 2,
                            LanguageCode = "PT",
                            Text = "Voltar para Homepage",
                            TokenValue = "#(goBackToHome)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 3,
                            LanguageCode = "PT",
                            Text = "Carregue no botão para retomar para a homepage.",
                            TokenValue = "#(goBackToHomeToolTip)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 4,
                            LanguageCode = "PT",
                            Text = "Ver detalhes",
                            TokenValue = "#(cardDetails)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 5,
                            LanguageCode = "PT",
                            Text = "Cancelar",
                            TokenValue = "#(Cancel)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 6,
                            LanguageCode = "PT",
                            Text = "Editar",
                            TokenValue = "#(edit)",
                            TranslationCategoryValue = "_tableText"
                        },
                        new
                        {
                            ID = 7,
                            LanguageCode = "PT",
                            Text = "Remover",
                            TokenValue = "#(remove)",
                            TranslationCategoryValue = "_tableText"
                        },
                        new
                        {
                            ID = 8,
                            LanguageCode = "PT",
                            Text = "Página de Teste de Componentes",
                            TokenValue = "#(TestPage Title)",
                            TranslationCategoryValue = "_TestPage"
                        },
                        new
                        {
                            ID = 9,
                            LanguageCode = "PT",
                            Text = "Janeiro",
                            TokenValue = "#(January)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 10,
                            LanguageCode = "PT",
                            Text = "Fevereiro",
                            TokenValue = "#(February)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 11,
                            LanguageCode = "PT",
                            Text = "Março",
                            TokenValue = "#(March)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 12,
                            LanguageCode = "PT",
                            Text = "Abril",
                            TokenValue = "#(April)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 13,
                            LanguageCode = "PT",
                            Text = "Maio",
                            TokenValue = "#(May)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 14,
                            LanguageCode = "PT",
                            Text = "Junho",
                            TokenValue = "#(June)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 15,
                            LanguageCode = "PT",
                            Text = "Julho",
                            TokenValue = "#(July)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 16,
                            LanguageCode = "PT",
                            Text = "Agosto",
                            TokenValue = "#(August)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 17,
                            LanguageCode = "PT",
                            Text = "Setembro",
                            TokenValue = "#(September)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 18,
                            LanguageCode = "PT",
                            Text = "Outubro",
                            TokenValue = "#(October)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 19,
                            LanguageCode = "PT",
                            Text = "Novembro",
                            TokenValue = "#(November)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 20,
                            LanguageCode = "PT",
                            Text = "Dezembro",
                            TokenValue = "#(December)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 21,
                            LanguageCode = "PT",
                            Text = "Seg",
                            TokenValue = "#(Mon)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 22,
                            LanguageCode = "PT",
                            Text = "Ter",
                            TokenValue = "#(Tue)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 23,
                            LanguageCode = "PT",
                            Text = "Qua",
                            TokenValue = "#(Wed)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 24,
                            LanguageCode = "PT",
                            Text = "Qui",
                            TokenValue = "#(Thu)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 25,
                            LanguageCode = "PT",
                            Text = "Sex",
                            TokenValue = "#(Fri)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 26,
                            LanguageCode = "PT",
                            Text = "Sab",
                            TokenValue = "#(Sat)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 27,
                            LanguageCode = "PT",
                            Text = "Dom",
                            TokenValue = "#(Sun)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 28,
                            LanguageCode = "PT",
                            Text = "KRF",
                            TokenValue = "#(krf)",
                            TranslationCategoryValue = "_brand"
                        },
                        new
                        {
                            ID = 29,
                            LanguageCode = "PT",
                            Text = "Utilizador",
                            TokenValue = "#(User)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 30,
                            LanguageCode = "PT",
                            Text = "Administração",
                            TokenValue = "#(Administration)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 31,
                            LanguageCode = "PT",
                            Text = "Sair",
                            TokenValue = "#(Logout)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 32,
                            LanguageCode = "PT",
                            Text = "Teste 1",
                            TokenValue = "#(Test1)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 33,
                            LanguageCode = "PT",
                            Text = "Teste 2",
                            TokenValue = "#(Test2)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 34,
                            LanguageCode = "PT",
                            Text = "Sub-Menu 1",
                            TokenValue = "#(SubTest1)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 35,
                            LanguageCode = "PT",
                            Text = "Sub-Menu 2",
                            TokenValue = "#(SubTest2)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 36,
                            LanguageCode = "PT",
                            Text = "Utilizador",
                            TokenValue = "#(Username)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 37,
                            LanguageCode = "PT",
                            Text = "Palavra-Passe",
                            TokenValue = "#(Password)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 38,
                            LanguageCode = "PT",
                            Text = "Entrar",
                            TokenValue = "#(LoginButton)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 39,
                            LanguageCode = "PT",
                            Text = "Entrar",
                            TokenValue = "#(LoginDrop)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 40,
                            LanguageCode = "PT",
                            Text = "Registar",
                            TokenValue = "#(NewLogin)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 41,
                            LanguageCode = "PT",
                            Text = "Notificações",
                            TokenValue = "#(Tooltip)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 42,
                            LanguageCode = "PT",
                            Text = "Lista de Notificações",
                            TokenValue = "#(NotificationHeader)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 43,
                            LanguageCode = "PT",
                            Text = "De {0} até {1}",
                            TokenValue = "#(FromDateToDate)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 44,
                            LanguageCode = "PT",
                            Text = "Existem {0} notificações por ler de datas anteriores a {1}, clique aqui para vêr lista de não lidas",
                            TokenValue = "#(OldUnreadedNotification)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 45,
                            LanguageCode = "PT",
                            Text = "Ver Todas",
                            TokenValue = "#(ViewAll)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 46,
                            LanguageCode = "PT",
                            Text = "Sim",
                            TokenValue = "#(Yes)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 47,
                            LanguageCode = "PT",
                            Text = "Não",
                            TokenValue = "#(No)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 48,
                            LanguageCode = "PT",
                            Text = "Ok",
                            TokenValue = "#(Ok)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 49,
                            LanguageCode = "PT",
                            Text = "Cancelar",
                            TokenValue = "#(Cancel)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 50,
                            LanguageCode = "PT",
                            Text = "Modal Test 1 Pt",
                            TokenValue = "#(ModalTest1)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 51,
                            LanguageCode = "PT",
                            Text = "Modal Test 2 Pt",
                            TokenValue = "#(ModalTest2)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 52,
                            LanguageCode = "PT",
                            Text = "Aceitar Cookies",
                            TokenValue = "#(CookiesModal)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 53,
                            LanguageCode = "PT",
                            Text = "Esta página utiliza cookies para análise de informação. Seleccione sim se permite a utilização dos cookies a baixo.",
                            TokenValue = "#(CookiesModalDescription)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 54,
                            LanguageCode = "PT",
                            Text = "Este cookie destina-se à análise de dados. Este cookie será desativado se seleccionar não.",
                            TokenValue = "#(CookieAnalyticDescription)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 55,
                            LanguageCode = "PT",
                            Text = "Nome do Cookie",
                            TokenValue = "#(CookieKey)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 56,
                            LanguageCode = "PT",
                            Text = "Descrição",
                            TokenValue = "#(CookieDescription)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 57,
                            LanguageCode = "PT",
                            Text = "Nenhum",
                            TokenValue = "#(no_option)",
                            TranslationCategoryValue = "_dropdown"
                        },
                        new
                        {
                            ID = 58,
                            LanguageCode = "PT",
                            Text = "Opção 2",
                            TokenValue = "#(opt_2)",
                            TranslationCategoryValue = "_dropdown"
                        },
                        new
                        {
                            ID = 59,
                            LanguageCode = "EN",
                            Text = "Loading!",
                            TokenValue = "#(loadingText)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 60,
                            LanguageCode = "EN",
                            Text = "Go back to Homepage",
                            TokenValue = "#(goBackToHome)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 61,
                            LanguageCode = "EN",
                            Text = "Click at the button to return to homepage.",
                            TokenValue = "#(goBackToHomeToolTip)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 62,
                            LanguageCode = "EN",
                            Text = "View details",
                            TokenValue = "#(cardDetails)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 63,
                            LanguageCode = "EN",
                            Text = "Cancel",
                            TokenValue = "#(Cancel)",
                            TranslationCategoryValue = "_generic"
                        },
                        new
                        {
                            ID = 64,
                            LanguageCode = "EN",
                            Text = "Edit",
                            TokenValue = "#(edit)",
                            TranslationCategoryValue = "_tableText"
                        },
                        new
                        {
                            ID = 65,
                            LanguageCode = "EN",
                            Text = "Remove",
                            TokenValue = "#(remove)",
                            TranslationCategoryValue = "_tableText"
                        },
                        new
                        {
                            ID = 66,
                            LanguageCode = "EN",
                            Text = "Component Test Page",
                            TokenValue = "#(TestPage Title)",
                            TranslationCategoryValue = "_TestPage"
                        },
                        new
                        {
                            ID = 67,
                            LanguageCode = "EN",
                            Text = "January",
                            TokenValue = "#(January)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 68,
                            LanguageCode = "EN",
                            Text = "February",
                            TokenValue = "#(February)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 69,
                            LanguageCode = "EN",
                            Text = "March",
                            TokenValue = "#(March)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 70,
                            LanguageCode = "EN",
                            Text = "April",
                            TokenValue = "#(April)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 71,
                            LanguageCode = "EN",
                            Text = "May",
                            TokenValue = "#(May)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 72,
                            LanguageCode = "EN",
                            Text = "June",
                            TokenValue = "#(June)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 73,
                            LanguageCode = "EN",
                            Text = "July",
                            TokenValue = "#(July)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 74,
                            LanguageCode = "EN",
                            Text = "August",
                            TokenValue = "#(August)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 75,
                            LanguageCode = "EN",
                            Text = "September",
                            TokenValue = "#(September)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 76,
                            LanguageCode = "EN",
                            Text = "October",
                            TokenValue = "#(October)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 77,
                            LanguageCode = "EN",
                            Text = "November",
                            TokenValue = "#(November)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 78,
                            LanguageCode = "EN",
                            Text = "December",
                            TokenValue = "#(December)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 79,
                            LanguageCode = "EN",
                            Text = "Mon",
                            TokenValue = "#(Mon)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 80,
                            LanguageCode = "EN",
                            Text = "Tue",
                            TokenValue = "#(Tue)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 81,
                            LanguageCode = "EN",
                            Text = "Wed",
                            TokenValue = "#(Wed)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 82,
                            LanguageCode = "EN",
                            Text = "Thu",
                            TokenValue = "#(Thu)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 83,
                            LanguageCode = "EN",
                            Text = "Fri",
                            TokenValue = "#(Fri)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 84,
                            LanguageCode = "EN",
                            Text = "Sat",
                            TokenValue = "#(Sat)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 85,
                            LanguageCode = "EN",
                            Text = "Sun",
                            TokenValue = "#(Sun)",
                            TranslationCategoryValue = "_datePicker"
                        },
                        new
                        {
                            ID = 86,
                            LanguageCode = "EN",
                            Text = "KRF",
                            TokenValue = "#(krf)",
                            TranslationCategoryValue = "_brand"
                        },
                        new
                        {
                            ID = 87,
                            LanguageCode = "EN",
                            Text = "User",
                            TokenValue = "#(User)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 88,
                            LanguageCode = "EN",
                            Text = "Administration",
                            TokenValue = "#(Administration)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 89,
                            LanguageCode = "EN",
                            Text = "Logout",
                            TokenValue = "#(Logout)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 90,
                            LanguageCode = "EN",
                            Text = "Test 1",
                            TokenValue = "#(Test1)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 91,
                            LanguageCode = "EN",
                            Text = "Test 2",
                            TokenValue = "#(Test2)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 92,
                            LanguageCode = "EN",
                            Text = "Submenu 1",
                            TokenValue = "#(SubTest1)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 93,
                            LanguageCode = "EN",
                            Text = "Submenu 2",
                            TokenValue = "#(SubTest2)",
                            TranslationCategoryValue = "_menu"
                        },
                        new
                        {
                            ID = 94,
                            LanguageCode = "EN",
                            Text = "Username",
                            TokenValue = "#(Username)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 95,
                            LanguageCode = "EN",
                            Text = "Password",
                            TokenValue = "#(Password)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 96,
                            LanguageCode = "EN",
                            Text = "SignIn",
                            TokenValue = "#(LoginButton)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 97,
                            LanguageCode = "EN",
                            Text = "Login",
                            TokenValue = "#(LoginDrop)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 98,
                            LanguageCode = "EN",
                            Text = "SignUp",
                            TokenValue = "#(NewLogin)",
                            TranslationCategoryValue = "_loginform"
                        },
                        new
                        {
                            ID = 99,
                            LanguageCode = "EN",
                            Text = "Notifications",
                            TokenValue = "#(Tooltip)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 100,
                            LanguageCode = "EN",
                            Text = "Notification List",
                            TokenValue = "#(NotificationHeader)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 101,
                            LanguageCode = "EN",
                            Text = "From {0} to {1}",
                            TokenValue = "#(FromDateToDate)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 102,
                            LanguageCode = "EN",
                            Text = "There are {0} unreaded notifications from dates previous to {1}, click here to check full unread list",
                            TokenValue = "#(OldUnreadedNotification)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 103,
                            LanguageCode = "EN",
                            Text = "View All",
                            TokenValue = "#(ViewAll)",
                            TranslationCategoryValue = "_notificationMenu"
                        },
                        new
                        {
                            ID = 104,
                            LanguageCode = "EN",
                            Text = "Yes",
                            TokenValue = "#(Yes)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 105,
                            LanguageCode = "EN",
                            Text = "No",
                            TokenValue = "#(No)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 106,
                            LanguageCode = "EN",
                            Text = "Ok",
                            TokenValue = "#(Ok)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 107,
                            LanguageCode = "EN",
                            Text = "Cancel",
                            TokenValue = "#(Cancel)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 108,
                            LanguageCode = "EN",
                            Text = "Modal Test 1 en",
                            TokenValue = "#(ModalTest1)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 109,
                            LanguageCode = "EN",
                            Text = "Modal Test 2 en",
                            TokenValue = "#(ModalTest2)",
                            TranslationCategoryValue = "_modal"
                        },
                        new
                        {
                            ID = 110,
                            LanguageCode = "EN",
                            Text = "Allow Cookies",
                            TokenValue = "#(CookiesModal)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 111,
                            LanguageCode = "EN",
                            Text = "This page uses some cookies for analytics, select yes if you allow the use of cookies bellow.",
                            TokenValue = "#(CookiesModalDescription)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 112,
                            LanguageCode = "EN",
                            Text = "Cookie used for analytics, this cookie will be disabled if no is selected.",
                            TokenValue = "#(CookieAnalyticDescription)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 113,
                            LanguageCode = "EN",
                            Text = "Cookie Name",
                            TokenValue = "#(CookieKey)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 114,
                            LanguageCode = "EN",
                            Text = "Description",
                            TokenValue = "#(CookieDescription)",
                            TranslationCategoryValue = "_cookieModal"
                        },
                        new
                        {
                            ID = 115,
                            LanguageCode = "EN",
                            Text = "None",
                            TokenValue = "#(no_option)",
                            TranslationCategoryValue = "_dropdown"
                        },
                        new
                        {
                            ID = 116,
                            LanguageCode = "EN",
                            Text = "Option 2",
                            TokenValue = "#(opt_2)",
                            TranslationCategoryValue = "_dropdown"
                        });
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.TranslationCategory", b =>
                {
                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Value")
                        .HasName("PK_CATEGORIES");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Value = "_generic"
                        },
                        new
                        {
                            Value = "_tableText"
                        },
                        new
                        {
                            Value = "_TestPage"
                        },
                        new
                        {
                            Value = "_datePicker"
                        },
                        new
                        {
                            Value = "_brand"
                        },
                        new
                        {
                            Value = "_menu"
                        },
                        new
                        {
                            Value = "_loginform"
                        },
                        new
                        {
                            Value = "_notificationMenu"
                        },
                        new
                        {
                            Value = "_modal"
                        },
                        new
                        {
                            Value = "_cookieModal"
                        },
                        new
                        {
                            Value = "_dropdown"
                        });
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Homepage.HomePageData", b =>
                {
                    b.HasOne("KRFHomepage.Domain.Database.Common.Language", "Language")
                        .WithOne("HomePageData")
                        .HasForeignKey("KRFHomepage.Domain.Database.Homepage.HomePageData", "LanguageCode")
                        .HasConstraintName("FK_HOMEPAGE_LANGUAGECODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.ErrorTranslation", b =>
                {
                    b.HasOne("KRFHomepage.Domain.Database.Translations.ErrorCode", "ErrorCode")
                        .WithMany("ErrorTranslations")
                        .HasForeignKey("Code")
                        .HasConstraintName("FK_ErrorTranslation_ErrorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KRFHomepage.Domain.Database.Common.Language", "Language")
                        .WithMany("ErrorTranslations")
                        .HasForeignKey("LanguageCode")
                        .HasConstraintName("FK_ErrorTranslation_LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErrorCode");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.Translation", b =>
                {
                    b.HasOne("KRFHomepage.Domain.Database.Common.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageCode")
                        .HasConstraintName("FK_Translations_LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KRFHomepage.Domain.Database.Translations.Token", "Token")
                        .WithMany("Translations")
                        .HasForeignKey("TokenValue")
                        .HasConstraintName("FK_Translations_TokenValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KRFHomepage.Domain.Database.Translations.TranslationCategory", "TranslationCategory")
                        .WithMany("Translations")
                        .HasForeignKey("TranslationCategoryValue")
                        .HasConstraintName("FK_Translations_TranslationCategoryValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Token");

                    b.Navigation("TranslationCategory");
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Common.Language", b =>
                {
                    b.Navigation("ErrorTranslations");

                    b.Navigation("HomePageData");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.ErrorCode", b =>
                {
                    b.Navigation("ErrorTranslations");
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.Token", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("KRFHomepage.Domain.Database.Translations.TranslationCategory", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
